Lambda-School-Labs/CS10-employee-shift

front-end/package.json, front-end/yarn.lock, netlify.toml
Added README
Started netlify deployment by adding a toml file to route 
added redux and react-router packages
Runs locally
=> added netlify.toml and README init

front-end/src/components/Pages/Signin.js
i went threw and removed all calls to the reactstrap library
rough view - also changed the text type on the password input from text to password to cache the password in browser memory for quicker use
removed the dependency of react strap from the sign in page
=> Sripped Reactstrap

back-end/Pipfile, back-end/Pipfile.lock, back-end/Readme.md, back-end/employee_shift/settings.py, front-end/src/components/Pages/Settings.js, front-end/src/components/Pages/Signin.js, front-end/src/store/User/actions.js, front-end/src/store/User/reducer.js, front-end/src/styles/App.css, front-end/src/styles/settings.css
-installed cors and setup middleware in settings
connection to front-end
Yes, still able to run server locally and in heroku
=> -Added CORS Middleware

front-end/src/components/App.js, front-end/src/components/Pages/Landing.js, front-end/src/components/Pages/Signin.js, front-end/src/components/Pages/Signup.js, front-end/src/components/Pages/index.js, front-end/src/index.js, front-end/src/store/Employee/actions.js, front-end/src/store/User/actions.js, front-end/src/store/User/reducer.js
- Change .env variables to support react's build
- Add Sign Up page
- Add Sign Up redux action
- Add Log Out redux action
- Separate routing to App component
- Finish Private Routes
- Add getUser action on page load to check if user has a saved log in token (needs get user call to be finished)
- Lots of comments for TODOs/WIPs
Ran locally using `yarn start NODE_ENV=development` and .env.development variables
=> Log in & Private Routes

back-end/Readme.md
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Added routes

front-end/src/components/Atoms/Date.js, front-end/src/components/Atoms/Shift.js, front-end/src/components/Atoms/Totals.js, front-end/src/components/Molecules/ScheduleDay.js, front-end/src/components/Organisms/CalendarTopNav.js, front-end/src/components/Organisms/Schedule.js, front-end/src/components/Pages/Calendar.js, front-end/src/components/Pages/Dashboard.js, front-end/src/store/Shift/actions.js, front-end/src/store/User/actions.js
- Add to Calendar component:
* Totals, Shift, Date atoms
* TopNav and Schedule molecules
* Schedule organism
=> Add calendar organisms, molecules, and atoms

back-end/Readme.md, back-end/employee_shift/settings.py
For deployment we had to edit AUTH_PASSWORD_VALIDATORS to fix bug for sign up user 
=> -edited Readme.md to for correct route and edited AUTH_VALIDATORS

back-end/employee_shift/settings.py, back-end/stripe_payment/api.py, front-end/src/components/Pages/test_pages/CheckoutForm.js
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> -config api key for endpoint and changed url for create charge

back-end/Pipfile, back-end/Pipfile.lock, back-end/employee_shift/settings.py, back-end/stripe_payment/api.py, back-end/stripe_payment/inventory.py, back-end/stripe_payment/stripe_app.py, back-end/stripe_payment/stripe_types.py
Heroku does not like lowecase, had to modify for heroku to read key and added crud routes from stripe docs to perform crud methods for checkout flow
=> -modified key for HEROKU and added stripe crud

front-end/src/components/Organisms/landing_card.js, front-end/src/components/Organisms/landing_detail.js, front-end/src/components/Pages/Landing.js, front-end/src/styles/Landing.js, front-end/src/styles/LandingRef.css, front-end/src/styles/font.css
Worked on fixing some CSS issues, repositioning elements, background color, fixed spacing for the textBox elements. Starting on learn more page
-[X] yarn render
=> Worked on landing_detail component. Fixed spacing in textblocks

front-end/src/components/Pages/Dashboard.js, front-end/src/styles/Landing.js
changed the button styles on the landing page and fixed the bug that after the pag finishes loading they become unclickable
=> bug hotfix

front-end/src/components/Atoms/TimePicker.js, front-end/src/components/Molecules/HoODay.js, front-end/src/components/Molecules/PostShiftTime.js, front-end/src/components/Molecules/ScheduleShift.js, front-end/src/components/Molecules/ScheduleShiftUpdate.js, front-end/src/components/Organisms/HoO.js, front-end/src/components/Organisms/TopNav.js, front-end/src/components/Organisms/landing_detail.js, front-end/src/components/Pages/Calendar.js, front-end/src/components/Pages/Signin.js, front-end/src/components/Templates/main.js, front-end/src/store/Profile/actions.js, front-end/src/store/Profile/reducer.js, front-end/src/store/Shift/actions.js, front-end/src/store/Shift/reducer.js, front-end/src/styles/Calendar.js, front-end/src/styles/LandingRef.css, front-end/src/styles/Template--main.js, front-end/src/styles/signin.js
- Fix bug caused by css class names conflicting with Semantic
- Calendar styling
- Portal boundaries on create shift (need to add to update)
- Rework template
- Dynamic employees 
- Delete Shift fully functional
- Calendar ready for CRUD testing
=> Dynamic calendar

front-end/src/components/Organisms/landingLearn.js, front-end/src/components/Pages/Landing.js
=> Second attempt at PR

front-end/src/components/App.js, front-end/src/components/Atoms/TimePicker.js, front-end/src/components/Molecules/PostShiftTime.js, front-end/src/components/Molecules/ScheduleShift.js, front-end/src/components/Molecules/ScheduleShiftUpdate.js, front-end/src/components/Organisms/SideNav.js, front-end/src/components/Organisms/TimeOffRequests.js, front-end/src/components/Organisms/TopNav.js, front-end/src/components/Pages/Admin.js, front-end/src/components/Pages/Calendar.js, front-end/src/components/Pages/Dashboard.js, front-end/src/components/Pages/Signup.js, front-end/src/components/Pages/index.js, front-end/src/components/Templates/main.js, front-end/src/store/Shift/actions.js, front-end/src/store/Shift/reducer.js, front-end/src/styles/Calendar.js, front-end/src/styles/Template--main.js
- Dynamic nav-bar
- Undo Kyle's bug - nested h1's
- Fix bug in time formatting
- Update tested working
- CRUD tested (bug on update where shift changes day)
- Cleanup
=> Calendar CRUD

front-end/.env.local.development, front-end/src/styles/Landing.js, front-end/src/styles/LandingRef.css
Working on animation positioning
=> animation positioning

front-end/src/components/Organisms/landing_card.js, front-end/src/styles/Landing.js
animated sign in/up buttons on landing page
=> animated buttons on the landing page

front-end/package.json, front-end/public/index.html, front-end/public/manifest.json, front-end/src/components/Molecules/ScheduleShift.js, front-end/src/components/Molecules/ScheduleShiftUpdate.js, front-end/src/components/Organisms/AdminDetails.js, front-end/src/components/Organisms/AdminHours.js, front-end/src/components/Pages/Admin.js, front-end/src/components/Pages/Billing.js, front-end/src/components/Pages/Calendar.js, front-end/src/components/Pages/Signup.js, front-end/src/store/Shift/actions.js, front-end/src/styles/Admin.js, front-end/src/styles/Billing.js, front-end/src/styles/Calendar.js, front-end/yarn.lock
- Rough validation on registration page
- Billing Semantic UI
- Calendar bug fixes
- Some Admin panel progress
- Updates for name change
- Prettier dev dependency
- Bug with Calendar time conversions (jumping days, incorrect times)
- Bug with Calendar shifts pushing out the grid
=> Styling & Bug Fixes & Admin Panel

front-end/package.json, front-end/src/components/Organisms/HoO.js, front-end/src/components/Pages/Calendar.js, front-end/src/styles/Calendar.js
- Dynamic shift counter next to employee names
- Finish gaps - needs more styling and maybe handle more cases
=> Calendar HoO shift gaps

front-end/src/styles/Landing.js, front-end/src/styles/LandingRef.css
started media query for landing page
=> starting working on media query

front-end/src/components/Organisms/NewEmployee.js, front-end/src/store/Profile/actions.js, front-end/yarn.lock
=> Add new employee

back-end/shiftapp/api.py, back-end/shiftapp/serializers.py, back-end/shiftapp/tests.py, front-end/src/components/Pages/Settings.js, front-end/src/components/Pages/Signin.js, front-end/src/components/Pages/Signup.js, front-end/src/store/User/actions.js
Register form front-end and back-end validations, User Model testing
=> Register form front-end and back-end validations, User Model testing

front-end/src/components/Organisms/landing_card.js, front-end/src/tests/App.test.js
started testing on the landing page.
=> basic testing on landing page

back-end/shiftapp/serializers.py
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Create Employee bug fix

front-end/src/components/Organisms/AdminHours.js, front-end/src/components/Organisms/EmployeeCard.js, front-end/src/components/Organisms/NewEmployee.js, front-end/src/components/Pages/Admin.js, front-end/src/store/Profile/actions.js, front-end/src/store/Profile/reducer.js, front-end/src/store/hourOfOperation/reducer.js
Employee delete tested working
=> Employee delete tested working

README.md
Testing PR merge. Can someone try merging?
=> test PR merge
